- hosts: localhost
  become: yes
  tasks:
   - name: Install Git
     yum: name=git state=present
   - name: git clone
     git:
      repo: 'https://github.com/samuelokuneye/maven-web-application.git'
      dest: /home/ansible/maven-web-application